# Build rules for a C++ scratchpad.

cc_binary(
    name = "virtual",
    srcs = ["virtual.cc"],
)

cc_binary(
    name = "pure",
    srcs = ["pure.cc"],
)

cc_binary(
    name = "multipleinheritance",
    srcs = ["multipleinheritance.cc"],
)

cc_binary(
    name = "slicing",
    srcs = ["slicing.cc"],
)

cc_binary(
    name = "quiz12",
    srcs = ["quiz12.cc"],
)
