# Build rules for a C++ scratchpad.

cc_binary(
    name = "exceptions",
    srcs = ["exceptions.cc"],
    copts = [
        "-fexceptions",
    ],
)

cc_binary(
    name = "quiz",
    srcs = ["quiz.cc"],
    copts = [
        "-fexceptions",
    ],
)
