# Build rules for various threading tools

package(default_visibility = ["//visibility:public"])

cc_library(
    name = "sync",
    srcs = glob(["*.cc"]),
    hdrs = glob(["*.h"]),
)

cc_library(
    name = "waitgroup",
    srcs = ["waitgroup.cc"],
    hdrs = ["waitgroup.h"],
)
