# Proto library for common messages

load("//tools:buildrules.bzl", "proto_library")

package(default_visibility = ["//visibility:public"])

proto_library(
    name = "empty",
    protos = [
        "empty.proto",
    ],
)
