cc_library(
    name = "counter",
    srcs = [],
    hdrs = ["counter.h"],
    deps = [],
)

cc_test(
    name = "counter_test",
    srcs = ["counter_test.cc"],
    deps = [
        ":counter",
        "//third_party/googletest:gtest",
    ],
)

cc_library(
    name = "histogram",
    srcs = [],
    hdrs = ["histogram.h"],
    deps = [
    ],
)

cc_test(
    name = "histogram_test",
    srcs = ["histogram_test.cc"],
    deps = [
        ":histogram",
        "//third_party/googletest:gtest",
    ],
)

cc_library(
    name = "stats",
    srcs = [],
    hdrs = ["stats.h"],
    deps = [],
)
