# Build rules for a C++ scratchpad.

cc_binary(
    name = "templates",
    srcs = ["templates.cc"],
    deps = [":array"],
)

cc_library(
    name = "array",
    srcs = [],
    hdrs = ["array.h"],
)

cc_binary(
    name = "quiz",
    srcs = ["quiz.cc"],
)
